import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Navbar } from '@/components/navbar/navbar';
import { UserContextProvider } from '@/components/context/UserContext';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Corner Point Of Sales',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
      <Toaster/>
        <UserContextProvider>
        <Navbar/>
        {children}
        </UserContextProvider>

      </body>
    </html>
  );
}
